name: Update Panel Image

on:
  workflow_dispatch:
env:
    PANEL_PROJECT_NAME: pterodactyl-panel # Dockerhub project
jobs:
  build_push_panel:
    name: Build and Push Panel Container
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v2

    - id: prepare-docker-image-identifiers
      name: Prepare Docker Image Identifiers
      run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # - name: Read Version
    #   id: read_version
    #   run: |
    #     echo "::set-output name=version::$(grep -Po "PANEL_VERSION=\K[^ ]+" ./manifest/version.txt)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./manifest/panel
        file: ./manifest/panel/Dockerfile
        platforms: linux/amd64
        build-args: VERSION=${{ steps.read_version.outputs.version }}
        push: true
        tags: "ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.PANEL_PROJECT_NAME }}:latest"



# "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PANEL_PROJECT_NAME }}:${{ steps.read_version.outputs.version }}"